# Read apparent magnitude files generated by SHAM interpolation, and plot:
# - magnitude histograms
# - color histograms
# - color scatter plots
# - redshift histograms
# - absolute magnitude histograms
from matplotlib import pyplot as plt
import numpy as np

import directories

from load_sham_galaxies import load_sham_galaxies

from sham_model_constants import BLUE, RED

import sys
sys.path.append("..")
from desiimaginganalysis.load_processed_target_data import load_processed_target_data
from desiimaginganalysis.constants import BGS_BRIGHT

# Parameters for plotting
bin_count = 90
LINEWIDTH = 1.5
ALPHA = 0.5

# Color choices
blue = "#004488"
yellow = "#ddaa33"
red = "#bb5566"
orange = "#EE7733"
teal = "#009988"

plt.rcParams["font.size"] = "16"
plt.rcParams["savefig.pad_inches"] = 0.05
plt.rcParams["savefig.bbox"] = "tight"

# Number of particles (cube root) used in run
# This determines the path where the data is stored
PARTICLE_COUNT_PINOCCHIO = 2048
Z_DEPTH = 0.5
PINOCCHIO_REGION = "fullsky"
DESI_region = directories.DECaLS_NGC
run_id = 146

# Load galaxy data from SHAM
galaxies = load_sham_galaxies(
    particle_count=PARTICLE_COUNT_PINOCCHIO,
    z_depth=Z_DEPTH,
    pinocchio_region=PINOCCHIO_REGION,
    DESI_region=DESI_region,
    run_id=run_id,
)

print("Number of objects:", len(galaxies["mag_r"]))

# Separate red and blue galaxies
red_mask = galaxies["blue_red"] == RED
blue_mask = galaxies["blue_red"] == BLUE
red_galaxies = {k: v[red_mask] for k, v in galaxies.items()}
blue_galaxies = {k: v[blue_mask] for k, v in galaxies.items()}

####################
# Load DESI LS dataset
desi_galaxies = load_processed_target_data(regions={DESI_region}, extinction_correction=True, apply_mask=True)
bright_desi_galaxies_mask = np.where(desi_galaxies["BGS_TARGET"] == BGS_BRIGHT)[0]
desi_galaxies = {
    k: v[bright_desi_galaxies_mask]
    for k, v in desi_galaxies.items()
}

####################
# Determine binning for each color band
bins = {
    "g": np.linspace(15, 22, bin_count),
    "r": np.linspace(14, 20.5, bin_count),
    "z": np.linspace(15, 20.5, bin_count),
}

fig, axs = plt.subplots(nrows=1, ncols=3, sharey=True, figsize=(12.5, 5))
fig.subplots_adjust(wspace=0.15)
for ax, band in zip(axs, bins.keys()):
    if band == "r":
        desi_band = "r_primed"
    else:
        desi_band = band

    ax.hist(
        galaxies[f"mag_{band}"],
        bins=bins[band],
        color=blue,
        density=True,
        histtype="step",
        label="SHAM",
        linewidth=LINEWIDTH,
    )

    ax.hist(
        desi_galaxies[f"MAG_{desi_band.upper()}"],
        bins=bins[band],
        color=blue,
        alpha=ALPHA,
        density=True,
        histtype="stepfilled",
        label="DESI LS",
    )

    ax.set_xlim([14, 22])

    ax.set_xlabel(f"{band} mag")

    ax.grid()

    if band == "g":
        ax.legend(loc="upper left")

fig.supylabel("PDF")

fig.savefig("/cluster/home/lmachado/msc-thesis/simulations/images/mag_hist_simulated.pdf")

plt.show()

####################
# Plot g - r and r - z color histograms
# g - r
fig, axs = plt.subplots(nrows=1, ncols=2, sharey=True, figsize=(8, 5))
fig.subplots_adjust(wspace=0.15)

bins_color_histograms = np.linspace(-1, 2, bin_count)

axs[0].hist(
    galaxies["mag_g"] - galaxies["mag_r"],
    bins=bins_color_histograms,
    color=blue,
    density=True,
    histtype="step",
    label="SHAM",
    linewidth=LINEWIDTH,
)

axs[0].hist(
    desi_galaxies["MAG_G"] - desi_galaxies["MAG_R"],
    bins=bins_color_histograms,
    color=blue,
    alpha=ALPHA,
    density=True,
    histtype="stepfilled",
    label="DESI LS",
)

axs[0].set_xlim([0, 2])
axs[0].set_xlabel("g - r")
axs[0].grid()

# r - z
axs[1].hist(
    galaxies["mag_r"] - galaxies["mag_z"],
    bins=bins_color_histograms,
    color=blue,
    density=True,
    histtype="step",
    label="SHAM",
    linewidth=LINEWIDTH,
)

axs[1].hist(
    desi_galaxies["MAG_R"] - desi_galaxies["MAG_Z"],
    bins=bins_color_histograms,
    color=blue,
    alpha=ALPHA,
    density=True,
    histtype="stepfilled",
    label="DESI LS",
)

axs[1].set_xlim([0, 2])
axs[1].set_xlabel("r - z")
axs[1].grid()

fig.supylabel("PDF")

fig.savefig(f"/cluster/home/lmachado/msc-thesis/simulations/images/colors_hist_simulated.pdf")

plt.show()

exit() # TODO

####################
# Plot redshift distribution of reds and blues for each r-magnitude bin
rmag_bins = [
    [15, 16],
    [16, 17],
    [17, 18],
    [18, 19],
    [19, 19.5],
]
COLORS = {
    15: "C0",
    16: "C1",
    17: "C2",
    18: "C3",
    19: "C4",
}

LINESTYLES = {
    "blue": "solid",
    "red": "dashed",
}
HISTTYPES = {
    "blue": "step",
    "red": "stepfilled",
}
ALPHAS = {
    "blue": 1,
    "red": 0.4,
}

fig, ax = plt.subplots(1, 1)

for g, color in (
        (blue_galaxies, "blue"),
        (red_galaxies, "red"),
    ):

    for rmag_low, rmag_high in rmag_bins:
        tmp_mask = (g["mag_r"] >= rmag_low) & (g["mag_r"] < rmag_high)

        ax.hist(
            g["redshift"][tmp_mask],
            label=f"{rmag_low:.1f} < r < {rmag_high:.1f}, {color.capitalize()}",
            color=COLORS[rmag_low],
            bins=40,
            histtype=HISTTYPES[color],
            alpha=ALPHAS[color],
            density=True,
            lw=2,
            ls=LINESTYLES[color],
        )

ax.set_xlabel("Redshift")
ax.set_ylabel("PDF")

ax.set_xlim([0, 0.5])
ax.set_ylim([0, 25])

ax.set_title("Blue vs. Red galaxies, redshift distribution")

ax.legend(ncol=2)

ax.grid()

fig.savefig(f"/cluster/home/lmachado/msc-thesis/simulations/images/SHAM_redshift_distributions_{DESI_region}.pdf")

plt.show()

####################
# Plot abs. mag. distribution of reds and blues,
# to show that reds are brighter than blues
fig, ax = plt.subplots(1, 1)

for g, color in (
        (blue_galaxies, "blue"),
        (red_galaxies, "red"),
    ):

    ax.hist(
        g["abs_mag"],
        label=f"{color.capitalize()}",
        color=color,
        bins=40,
        histtype="step",
        density=True,
        lw=2,
        ls=LINESTYLES[color],
    )

ax.set_xlabel("Absolute Magnitude")
ax.set_ylabel("PDF")

ax.set_title("Blue vs. Red galaxies, absolute magnitude distribution")

ax.legend()

ax.grid()

fig.savefig(f"/cluster/home/lmachado/msc-thesis/simulations/images/SHAM_absmag_distributions_{DESI_region}.png")

plt.show()

