# Read apparent magnitude files generated by SHAM interpolation,
# and plot magnitude and color histograms

from matplotlib import pyplot as plt
import numpy as np

import directories

from load_sham_galaxies import load_sham_galaxies

# Parameters for plotting
bin_count = 70
LINEWIDTH = 1.5
ALPHA = 0.5

# Color choices
blue = "#004488"
yellow = "#ddaa33"
red = "#bb5566"
orange = "#EE7733"
teal = "#009988"

plt.rcParams['font.size'] = "12"

# Number of particles (cube root) used in run
# This determines the path where the data is stored
PARTICLE_COUNT_PINOCCHIO = 2048
Z_DEPTH = 0.5
PINOCCHIO_REGION = "fullsky"
DESI_region = directories.BASS_MzLS
run_id = 146

# Load galaxy data from SHAM
galaxies = load_sham_galaxies(
    particle_count=PARTICLE_COUNT_PINOCCHIO,
    z_depth=Z_DEPTH,
    pinocchio_region=PINOCCHIO_REGION,
    DESI_region=DESI_region,
    run_id=run_id,
)

print("Number of objects:", len(galaxies["mag_r"]))

# Determine binning for each color band
bins = {
    "g": np.linspace(15, 22, bin_count),
    "r": np.linspace(14, 20.5, bin_count),
    "z": np.linspace(15, 20.5, bin_count),
}

for band in bins.keys():
    plt.hist(
        galaxies[f"mag_{band}"],
        bins=bins[band],
        color=teal,
    )

    plt.xlim([14, 22])

    plt.title("SHAM apparent magnitudes, BASS-MzLS filters")
    plt.xlabel(f"{band} apparent magnitude")
    plt.ylabel("Count")

    plt.grid()
    plt.savefig(f"/cluster/home/lmachado/msc-thesis/simulations/images/{band}mag_hist_simulated.pdf")

    plt.show()
